// Generated by CoffeeScript 1.12.7
(function() {
  $(function() {
    var btn, container, field, img;
    container = $('input#field1016').parent();
    img = 'data:image/png;base64,';
    btn = $('<button width=><img src="../img/icon.png"></button>');
    field = $('input#field1016');
    console.log(field);
    btn.on('click', function() {
      if (/^http(s?):\/\//.test(field[0].value)) {
        window.open(field[0].value);
      }
    });
    container.append(btn);
  });

}).call(this);
